### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by enhui-huang** [enhui-huang/enhui-huang.github.io#1]
- [x] add posters and slides to "publication" part
- [x] reorder the log of "github","linkedin" at the bottom of the pages and slove "page not found" problem"
- [ ] complete "aboutme" page
- [ ] design the home page
- [ ] Figure how to change the color of a picture when you move the cursor onto that picture like the first blog. Need to better organize the posts.
- [ ] enlarge the avatar size
- [ ] find a better way to display news
